trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true
  
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- task: npmAuthenticate@0
  inputs:
    workingFile: .npmrc
  displayName: 'Authenticate npm'

- script: npm install
  displayName: 'npm install'

- script: npm run build
  displayName: 'npm run build'

- script: npx semantic-release
  displayName: 'semantic release'
  env:
    GH_TOKEN: $(GitHubToken)
    GIT_AUTHOR_NAME: $(Build.RequestedFor)
    GIT_AUTHOR_EMAIL: $(Build.RequestedForEmail)
    GIT_COMMITTER_NAME: Build Automation
    GIT_COMMITTER_EMAIL: support@cnect.com.au
  condition: and(always(), ne(variables['Build.Reason'], 'PullRequest'))
